### ISSUE TITLE
Mehrere Fehler im Abschnitt Vorspannen

### ISSUE THREAD

**Issue by lostMia** [lg-eng/HWE-Skript#1]
Im zweiten Absatz der Unterüberschrift  [#vorspannen](https://lg-eng.github.io/HWE-Skript/Transistoren/04_EinfuehrungProjekt.html#vorspannen) habe ich 3 Fehler gefunden, welche hier fett Markiert wurden:
Fehler wurden durchgestrichen und die Verbesserung daneben fett markiert.

> Mittels DC-Sweep kann die Spannungsquelle auf einen gewünschten eingestellt werden. Der ist so zu wählen, dass der Arbeitspunkt außerhalb des nichtlinearen Bereichs der Transistorkennlinie ~~liegt ist~~ **liegt**. Gleichzeitig soll er so klein ~~als~~ **wie** Möglich sein um die Verluste gering zu halten. Hier ~~soll der soll~~ **soll dieser** ein Zehntel des maximalen Laststromes betragen. 

Mfg Mia Unterladstätter

**Comment by lg-eng** [comment]
Danke, wird im nächsten Update korrigiert.
