### ISSUE TITLE
Noch mehr Fehler im Abschnitt Vorspannen

### ISSUE THREAD

**Issue by lostMia** [lg-eng/HWE-Skript#2]
Hier noch mehr gefundene Fehler, diesmal im dritten Absatz der Überschrift  [#vorspannen](https://lg-eng.github.io/HWE-Skript/Transistoren/04_EinfuehrungProjekt.html#vorspannen)
Fehler wurden durchgestrichen, die Verbesserung daneben fett markiert.

> Da es sich um unterschiedliche Transistoren handelt **[Beistrich vergessen]** ist natürlich auch der Zusammenhang zwischen Ube und Ic ein ~~anderen~~ **anderer**. Da die Werte sehr nahe beieinander liegen kann ein gerundetes arithmetisches Mittel als Ergebnis für Vvor verwendet werden. Der Verstärker hat nun eine Qualität, welche das Verstärken von niederfrequenten Signalen in ausreichender Güte erlaubt **[Beistrich vergessen]** um Beispielsweise Musik zu verstärken. Dies ist am geringen Unterschied zwischen der Eingangsspannung ~~under~~ **und der** Ausgangsspannung zu erkennen.

Mfg Mia Unterladstätter

**Comment by lg-eng** [comment]
Danke, wird korrigiert.
